### PR TITLE
Use the DxGrid instead of the obsolete DxDataGrid

### PR DESCRIPTION
**Pull request by dtemme**
1. The DxDataGrid from DevExpress is obsolete and should be replaced with the rewritten DxGrid. (https://docs.devexpress.com/Blazor/403162/grid/migrate-from-data-grid-to-grid)
2. The currently used DevExpress 20.1.x version is more than 2 years old and there are already 2 major updates available.

### CODE REVIEW

**Comment by mrpmorris** [comment]
I used the installer from their website, and checked for package updates and there were none.
image

Where did you get this newer version from?

**Comment by dtemme** [comment]
If you visit https://www.devexpress.com/ClientCenter/DownloadManager/ and you are logged in (having a valid license) you get a user defined NuGet-package feed URL - see also https://nuget.devexpress.com/#feed-url

**Comment by dtemme** [comment]
I installed the trial version today on a test machine without a license and got the latest version (22.2.3) including a local NuGet feed as described in the documentation https://docs.devexpress.com/GeneralInformation/401140/installation/install-devexpress-controls-using-nuget-packages/local-nuget-feed

**Comment by mrpmorris** [comment]
This is still just as slow - can you set it to a fixed height of 800px and make it virtualized? Does that improve performance?

**Pull request merged**
