### PR TITLE
Add Blazorise project

### PR DESCRIPTION
**Pull request by stsrki**

### CODE REVIEW

**Comment by mrpmorris** [comment]
Could you enable grouping and submit another please? Thanks :)

**Comment by stsrki** [comment]
We don't have a grouping ATM.

**Comment by stsrki** [comment]
PS. Can you update your results? I  have a different system than yours, so it doesn't make sense to write it.

**Comment by mrpmorris** [comment]
My test is for both initial load and grouping so I can't include it, sorry.

**Comment by stsrki** [comment]
Can't you just put N/A like you already did for others?

image

**Comment by mrpmorris** [comment]
The N/A is there because when you group it collapses the groups, which is faster so I don't count it.

They do group though, which is why there is an Expand/Collapse column.

**Pull request merged**
